# Project Name
TARGET = rings-reverb

# Sources
CPP_SOURCES = rings-reverb.cpp

# Library Locations
LIBDAISY_DIR = ../../lib/libDaisy

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

C_INCLUDES += -I../../lib/eurorack